# hearth with color
import turtle
t=turtle
t.bgcolor("burlywood1")
t.pencolor("black")
t.pencolor("red")
t.pensize(6)
t.speed(0)
t.color("black")
t.begin_fill()
t.fd(1)
t.lt(40)
t.fd(90)
for n in range(13):
	t.forward(7)
	t.left(9)
	t.forward(7)
	t.left(9)
t.forward(1)
t.right(170)
t.forward(10)
t.end_fill()
t.color("red")
t.begin_fill()
for n in range(12):
	t.forward(7)
	t.left(9)
	t.forward(7)
	t.left(9)
t.fd(98)
t.end_fill()
t.penup()
t.color('black')
t.pensize(12)
t.right(35)
t.forward(50)
t.hideturtle()
t.write('Mostly true love ends with tears only...')
t.penup()
t.left(10)
t.forward(300)
t.pendown()
t.width(1)
t.write('Varun Kumar Reddy Poli',90,align='right')

t.exitonclick()
