# turtle heart symbol project
import turtle
for i in range(20):
   turtle.speed(50)
   turtle.penup()
   turtle.width(10)
   turtle.color('blue2')
   turtle.left(45)
   turtle.color('blue2')
   turtle.forward(100)
   turtle.color('blue2')
   turtle.circle(50,180)
   turtle.pendown()
   turtle.color('deeppink')
   turtle.right(90)
   turtle.color('deeppink')
   turtle.circle(50,180)
   turtle.color('deeppink')
   turtle.forward(100)
   turtle.color('deeppink')
   turtle.clear()
   turtle.left(45)
   turtle.pendown()
   turtle.width(10)
   turtle.color('cyan')
   turtle.left(45)
   turtle.color('cyan')
   turtle.forward(100)
   turtle.color('cyan')
   turtle.circle(50,180)
   turtle.color('cyan')
   turtle.right(90)
   turtle.color('cyan')
   turtle.circle(50,180)
   turtle.color('cyan')
   turtle.forward(100)
   turtle.color('cyan')
   turtle.left(45)
   turtle.clear()
   turtle.pendown()
   turtle.color('coral')
   turtle.left(45)
   turtle.color('coral')
   turtle.forward(100)
   turtle.color('coral')
   turtle.circle(50,180)
   turtle.color('coral')
   turtle.penup()
   turtle.right(90)
   turtle.circle(50,180)
   turtle.forward(100)
   turtle.left(45)
   turtle.clear()

turtle.color('red')
turtle.begin_fill()
turtle.left(45)
turtle.forward(100)
turtle.circle(50,180)
turtle.right(90)
turtle.circle(50,180)
turtle.forward(100)
turtle.ht()
turtle.end_fill()
turtle.forward(100)
turtle.write('Love u all \n POLI VARUN KUMAR REDDY',font=('Arial',10))


turtle.mainloop()