# loading symbol
from turtle import*
for i in range(30):
    width(4)
    hideturtle()
    speed(12)
    color('red')
    fd(30)
    bk(30)
    penup()
    rt(109)
    fd(20)
    lt(79)
    color('orange')
    pendown()
    fd(30)
    bk(30)
    penup()
    rt(109)
    fd(20)
    lt(79)
    color('green')
    pendown()
    fd(30)
    bk(30)
    penup()
    rt(109)
    fd(20)
    lt(79)
    clear()
    pendown()
penup()
fd(70)
write('VARUN KUMAR REDDY POLI',font=('Arial',10))

exitonclick()